version: '3.9'
services:
  django-app:
    image: django-app:hello-world-i-am-just-start-using-docker
    container_name: django-app-container
    build: ./
    volumes:
      - ./:/django
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000